oc_platform:
    resource: "@DocBundle/Resources/config/routing.yml"
    prefix:   /
    
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#api:
 #   resource: "."
  #  type:     "api"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api_login_check:
   path: /api/login_check