file:
    path:     /
    defaults: { _controller: "DocBundle:File:index" }

file_show:
    path:     /{id}/show
    defaults: { _controller: "DocBundle:File:show" }

file_new:
    path:     /new
    defaults: { _controller: "DocBundle:File:new" }

file_create:
    path:     /create
    defaults: { _controller: "DocBundle:File:create" }
    methods:  POST

file_edit:
    path:     /{id}/edit
    defaults: { _controller: "DocBundle:File:edit" }

file_update:
    path:     /{id}/update
    defaults: { _controller: "DocBundle:File:update" }
    methods:  [POST, PUT]

file_delete:
    path:     /{id}/delete
    defaults: { _controller: "DocBundle:File:delete" }
